const classesByDay = {
  Monday: [
    {
      name: 'Power Strength',
      time: '6:00 AM – 7:00 AM',
      trainer: 'Rajesh Kumar',
      description: 'Barbell compound movements — squat, bench, deadlift, overhead press — programmed in a progressive 5×5 framework. Weights go up each week. Bring your lifting shoes.',
      level: 'Intermediate',
      duration: '60 min',
      spots: 15,
    },
    {
      name: 'Yoga Flow',
      time: '7:30 AM – 8:30 AM',
      trainer: 'Sneha Patel',
      description: 'A moving vinyasa practice — sun salutations, standing sequences, and held poses. Builds flexibility and body awareness. Quiet, focused, and consistently challenging.',
      level: 'All Levels',
      duration: '60 min',
      spots: 20,
    },
    {
      name: 'HIIT Cardio',
      time: '5:00 PM – 6:00 PM',
      trainer: 'Vikram Singh',
      description: 'Work-to-rest intervals designed to push your aerobic ceiling. Forty seconds on, twenty off — structured cycles, tracked output. Not comfortable. Effective.',
      level: 'Advanced',
      duration: '60 min',
      spots: 12,
    },
    {
      name: 'Boxing Fitness',
      time: '6:30 PM – 7:30 PM',
      trainer: 'Arjun Reddy',
      description: 'Jabs, crosses, hooks, and footwork — combinations built on correct technique before intensity. Develops coordination, upper-body endurance, and reaction time. No prior boxing required.',
      level: 'Intermediate',
      duration: '60 min',
      spots: 15,
    },
    {
      name: 'Dance Conditioning',
      time: '8:00 PM – 9:00 PM',
      trainer: 'Neha Kapoor',
      description: 'Rhythmic movement patterns set to music — works cardiovascular fitness, footwork timing, and hip mobility. High energy, low impact on the joints.',
      level: 'All Levels',
      duration: '60 min',
      spots: 25,
    },
  ],
  Tuesday: [
    {
      name: 'Indoor Cycling',
      time: '6:00 AM – 7:00 AM',
      trainer: 'Amit Verma',
      description: 'Structured interval rides — flat efforts, sprints, and climb simulations. Output is tracked on each bike. RPE guidance given throughout. No experience required, just effort.',
      level: 'Intermediate',
      duration: '60 min',
      spots: 18,
    },
    {
      name: 'Pilates Core',
      time: '10:00 AM – 11:00 AM',
      trainer: 'Sneha Patel',
      description: 'Mat-based Pilates focused on deep core activation, spinal alignment, and hip stability. Works the muscles that hold your posture and protect your lower back.',
      level: 'Beginner',
      duration: '60 min',
      spots: 15,
    },
    {
      name: 'CrossFit WOD',
      time: '5:30 PM – 6:30 PM',
      trainer: 'Rohit Malhotra',
      description: 'Daily programmed workout combining strength lifts, gymnastics movements, and metabolic conditioning. Scaled options available. Time yourself, track your score.',
      level: 'Advanced',
      duration: '60 min',
      spots: 12,
    },
    {
      name: 'Yoga Restore',
      time: '7:00 PM – 8:00 PM',
      trainer: 'Sneha Patel',
      description: 'Long-held passive stretches targeting common tightness points — hip flexors, thoracic spine, hamstrings. Props provided. Designed to recover the body between harder training sessions.',
      level: 'All Levels',
      duration: '60 min',
      spots: 20,
    },
  ],
  Wednesday: [
    {
      name: 'Power Strength',
      time: '6:00 AM – 7:00 AM',
      trainer: 'Rajesh Kumar',
      description: 'Barbell compound movements — squat, bench, deadlift, overhead press — programmed in a progressive 5×5 framework. Weights go up each week. Bring your lifting shoes.',
      level: 'Intermediate',
      duration: '60 min',
      spots: 15,
    },
    {
      name: 'Functional Training',
      time: '11:00 AM – 12:00 PM',
      trainer: 'Sanjay Gupta',
      description: 'Movement patterns that carry over to real life: carries, hinges, rotations, and single-leg work. Addresses asymmetries and improves how the body moves under load.',
      level: 'Intermediate',
      duration: '60 min',
      spots: 14,
    },
    {
      name: 'Kickboxing',
      time: '5:00 PM – 6:00 PM',
      trainer: 'Kavya Menon',
      description: 'Stand-up striking combinations — punches and kicks drilled in sequence on pads. Develops timing, coordination, and conditioning simultaneously.',
      level: 'Intermediate',
      duration: '60 min',
      spots: 15,
    },
    {
      name: 'Indoor Cycling',
      time: '6:30 PM – 7:30 PM',
      trainer: 'Amit Verma',
      description: 'Evening ride — endurance base building with tempo intervals. Lower intensity than the morning session. Good for active recovery days between heavier training.',
      level: 'All Levels',
      duration: '60 min',
      spots: 18,
    },
    {
      name: 'Stretch & Restore',
      time: '8:00 PM – 9:00 PM',
      trainer: 'Sneha Patel',
      description: 'A guided end-of-day session: breathing techniques, progressive muscle relaxation, and floor-based mobility work. Systematic, not casual.',
      level: 'All Levels',
      duration: '60 min',
      spots: 25,
    },
  ],
  Thursday: [
    {
      name: 'Athletic Conditioning',
      time: '6:00 AM – 7:00 AM',
      trainer: 'Vikram Singh',
      description: 'Strength-endurance circuits drawn from athletic training principles. Kettlebells, sleds, carries, and battle ropes programmed in rounds. Hard from the first minute.',
      level: 'Advanced',
      duration: '60 min',
      spots: 12,
    },
    {
      name: 'Yoga Flow',
      time: '7:30 AM – 8:30 AM',
      trainer: 'Sneha Patel',
      description: 'A moving vinyasa practice — sun salutations, standing sequences, and held poses. Builds flexibility and body awareness. Quiet, focused, and consistently challenging.',
      level: 'All Levels',
      duration: '60 min',
      spots: 20,
    },
    {
      name: 'Boxing Fitness',
      time: '5:30 PM – 6:30 PM',
      trainer: 'Arjun Reddy',
      description: 'Jabs, crosses, hooks, and footwork — combinations built on correct technique before intensity. Develops coordination, upper-body endurance, and reaction time.',
      level: 'Intermediate',
      duration: '60 min',
      spots: 15,
    },
    {
      name: 'HIIT Cardio',
      time: '7:00 PM – 8:00 PM',
      trainer: 'Rohit Malhotra',
      description: 'Work-to-rest intervals designed to push your aerobic ceiling. Forty seconds on, twenty off — structured cycles, tracked output. Not comfortable. Effective.',
      level: 'Advanced',
      duration: '60 min',
      spots: 12,
    },
  ],
  Friday: [
    {
      name: 'Indoor Cycling',
      time: '6:00 AM – 7:00 AM',
      trainer: 'Amit Verma',
      description: 'A focused morning ride to open the week. Steady-state aerobic effort with sprint finishes. Good for members who train weights later in the day.',
      level: 'All Levels',
      duration: '60 min',
      spots: 18,
    },
    {
      name: 'Power Strength',
      time: '10:00 AM – 11:00 AM',
      trainer: 'Rajesh Kumar',
      description: 'Barbell compound movements — squat, bench, deadlift, overhead press — programmed in a progressive 5×5 framework. Weights go up each week. Bring your lifting shoes.',
      level: 'Intermediate',
      duration: '60 min',
      spots: 15,
    },
    {
      name: 'Dance Conditioning',
      time: '5:00 PM – 6:00 PM',
      trainer: 'Neha Kapoor',
      description: 'Rhythmic movement patterns set to music — works cardiovascular fitness, footwork timing, and hip mobility. High energy, low impact on the joints.',
      level: 'All Levels',
      duration: '60 min',
      spots: 25,
    },
    {
      name: 'CrossFit WOD',
      time: '6:30 PM – 7:30 PM',
      trainer: 'Rohit Malhotra',
      description: 'End-of-week programming — typically a heavier strength component followed by a scored conditioning piece. Scaled options available.',
      level: 'Advanced',
      duration: '60 min',
      spots: 12,
    },
    {
      name: 'Yoga & Breathwork',
      time: '8:00 PM – 9:00 PM',
      trainer: 'Sneha Patel',
      description: 'A deliberate end to the training week — breath-led sequences, grounding postures, and guided relaxation. Reduces cortisol, improves sleep quality.',
      level: 'All Levels',
      duration: '60 min',
      spots: 20,
    },
  ],
  Saturday: [
    {
      name: 'Yoga Flow',
      time: '7:00 AM – 8:00 AM',
      trainer: 'Sneha Patel',
      description: 'Start the weekend with a longer, unhurried practice. More time in each pose, more transitions, a complete session from warm-up through savasana.',
      level: 'All Levels',
      duration: '60 min',
      spots: 20,
    },
    {
      name: 'Athletic Conditioning',
      time: '9:00 AM – 10:00 AM',
      trainer: 'Vikram Singh',
      description: 'Strength-endurance circuits drawn from athletic training principles. Kettlebells, sleds, carries, and battle ropes programmed in rounds. Hard from the first minute.',
      level: 'Advanced',
      duration: '60 min',
      spots: 12,
    },
    {
      name: 'Indoor Cycling',
      time: '11:00 AM – 12:00 PM',
      trainer: 'Amit Verma',
      description: 'Weekend long ride — 50 minutes of progressive effort with a 10-minute warm-down. Endurance-focused. Good for runners and cross-training athletes.',
      level: 'Intermediate',
      duration: '60 min',
      spots: 18,
    },
    {
      name: 'Dance Conditioning',
      time: '4:00 PM – 5:00 PM',
      trainer: 'Neha Kapoor',
      description: 'Rhythmic movement patterns set to music — works cardiovascular fitness, footwork timing, and hip mobility. High energy, low impact on the joints.',
      level: 'All Levels',
      duration: '60 min',
      spots: 25,
    },
    {
      name: 'Boxing Fitness',
      time: '5:30 PM – 6:30 PM',
      trainer: 'Arjun Reddy',
      description: 'Saturday evening boxing — same technical focus as weekday sessions, with a conditioning finisher. Expect to leave with your shoulders fatigued.',
      level: 'Intermediate',
      duration: '60 min',
      spots: 15,
    },
  ],
  Sunday: [
    {
      name: 'Yoga & Meditation',
      time: '8:00 AM – 9:00 AM',
      trainer: 'Sneha Patel',
      description: 'An intentional Sunday session — restorative postures, seated breath work, and guided body scan. Resets the nervous system before the week starts.',
      level: 'All Levels',
      duration: '60 min',
      spots: 20,
    },
    {
      name: 'Pilates Core',
      time: '10:00 AM – 11:00 AM',
      trainer: 'Sneha Patel',
      description: 'Mat-based Pilates focused on deep core activation, spinal alignment, and hip stability. Works the muscles that hold your posture and protect your lower back.',
      level: 'Beginner',
      duration: '60 min',
      spots: 15,
    },
    {
      name: 'Functional Training',
      time: '4:00 PM – 5:00 PM',
      trainer: 'Sanjay Gupta',
      description: 'Movement patterns that carry over to real life: carries, hinges, rotations, and single-leg work. Addresses asymmetries and improves how the body moves under load.',
      level: 'Intermediate',
      duration: '60 min',
      spots: 14,
    },
    {
      name: 'Indoor Cycling',
      time: '5:30 PM – 6:30 PM',
      trainer: 'Amit Verma',
      description: 'Sunday evening ride to close out the week on a high note. Low pressure, conversational effort — designed for active recovery, not peak output.',
      level: 'All Levels',
      duration: '60 min',
      spots: 18,
    },
  ],
};

export default classesByDay;
